apiVersion: v1
kind: Service

metadata:
  name: cloudnative-service

spec:
  selector:
    app: cloudnative   # matches Deployment labels
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 8080  # Container port
  type: ClusterIP
