apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cloudnative.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "cloudnative.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
