apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greetingservice
          image: greetingservice:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
