name: CI - Build Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build CloudNativeApp image
        run: |
          docker build \
            -t cloudnativeapp:latest \
            -f CloudNativeApp/Dockerfile \
            CloudNativeApp

      - name: Build GreetingService image
        run: |
          docker build \
            -t greetingservice:latest \
            -f GreetingService/Dockerfile \
            GreetingService
